export { Navbar } from "./navbar"
export { Hero } from "./hero"
export { SocialProof } from "./social-proof"
export { Statement } from "./statement"
export { ProductSections } from "./product-sections"
export { Comparison } from "./comparison"
export { CTA } from "./cta"
export { Footer } from "./footer"
